[[buildpacks]]
# Packaged buildpacks to include in builder;
# the "hello-universe" package contains the "hello-world" and "hello-moon" buildpacks
uri = "docker://registry.iximiuz.com/examples/buildpacks/golang-buildpack"
version = "0.0.1"

[[order]]
[[order.group]]
id = "registry.iximiuz.com/examples/buildpacks/golang-buildpack"
version = "0.0.1"

# Base images used to create the builder
[build]
image = "registry.iximiuz.com/examples/images/golang-builder"
[run]
[[run.images]]
image = "registry.iximiuz.com/examples/images/golang-runner"

