name: Pack Build

on:
  workflow_dispatch:

permissions:
  contents: write # required to create a release

jobs:
  zip-artifacts:
    strategy:
      matrix:
        folders:
          - "creating-docker-images-without-writing-dockerfiles-using-buildpacks-4c989678/examples/golang-hello"
          - "creating-docker-images-without-writing-dockerfiles-using-buildpacks-4c989678/examples/python-hello"
          - "creating-docker-images-without-writing-dockerfiles-using-buildpacks-4c989678/examples/nodejs-hello"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pack CLI
        shell: bash
        run: |
          wget https://github.com/buildpacks/pack/releases/download/v0.40.9/pack-v0.40.9-linux.tgz

          tar -xvf pack-v0.40.9-linux.tgz

          sudo mv pack /usr/local/bin

      - name: Build Image
        shell: bash
        working-directory: ${{ matrix.folders }}
        run: |
          pack build app --builder heroku/builder:26
